### ISSUE TITLE
Optional time formats

### ISSUE THREAD

**Issue by feldrim** [nerezo/giftubebot#1]
Adding to hh:mm:ss
1. No hours: mm:ss
2. Just dots: hh.mm.ss & mm.ss

**Comment by feldrim** [comment]
Errors about time format occured while generating gif.
1.  `start time should be in this format "hh:mm:ss". i.e. "00:12:30". Please try again.` message when using **01.00** as start time.
   ![screenshot 472](https://cloud.githubusercontent.com/assets/15658960/16123108/79a2fa9e-33f2-11e6-9fe1-962384608554.png)
2. `Please give a start time in the duration of the video! Please try again.` message when using **1.00** as start time.
   ![screenshot 473](https://cloud.githubusercontent.com/assets/15658960/16123109/79a5774c-33f2-11e6-8267-e133e4de2249.png)

**Comment by nerezo** [comment]
there was dot style duration value support with previous version but I removed that to be able to supporting milliseconds with the parameters now.

besides that it is normal to showing "Please give a start time in the duration of the video! Please try again.
/gifthelp" message when you pass time values outside of the duration of a video.
